export const allCountriesRU = [
    { code: "af", name: "Афганистан" },
    { code: "al", name: "Албания" },
    { code: "dz", name: "Алжир" },
    { code: "ad", name: "Андорра" },
    { code: "ao", name: "Ангола" },
    { code: "ag", name: "Антигуа и Барбуда" },
    { code: "ar", name: "Аргентина" },
    { code: "am", name: "Армения" },
    { code: "au", name: "Австралия" },
    { code: "at", name: "Австрия" },
    { code: "az", name: "Азербайджан" },
    { code: "bs", name: "Багамы" },
    { code: "bh", name: "Бахрейн" },
    { code: "bd", name: "Бангладеш" },
    { code: "bb", name: "Барбадос" },
    { code: "by", name: "Беларусь" },
    { code: "be", name: "Бельгия" },
    { code: "bz", name: "Белиз" },
    { code: "bj", name: "Бенин" },
    { code: "bt", name: "Бутан" },
    { code: "bo", name: "Боливия" },
    { code: "ba", name: "Босния и Герцеговина" },
    { code: "bw", name: "Ботсвана" },
    { code: "br", name: "Бразилия" },
    { code: "bn", name: "Бруней" },
    { code: "bg", name: "Болгария" },
    { code: "bf", name: "Буркина-Фасо" },
    { code: "bi", name: "Бурунди" },
    { code: "cv", name: "Кабо-Верде" },
    { code: "kh", name: "Камбоджа" },
    { code: "cm", name: "Камерун" },
    { code: "ca", name: "Канада" },
    { code: "cf", name: "Центральноафриканская Республика" },
    { code: "td", name: "Чад" },
    { code: "cl", name: "Чили" },
    { code: "cn", name: "Китай" },
    { code: "co", name: "Колумбия" },
    { code: "km", name: "Коморы" },
    { code: "cg", name: "Республика Конго" },
    { code: "cd", name: "Демократическая Республика Конго" },
    { code: "cr", name: "Коста-Рика" },
    { code: "hr", name: "Хорватия" },
    { code: "cu", name: "Куба" },
    { code: "cy", name: "Кипр" },
    { code: "cz", name: "Чехия" },
    { code: "ci", name: "Кот-д'Ивуар" },
    { code: "dk", name: "Дания" },
    { code: "dj", name: "Джибути" },
    { code: "dm", name: "Доминика" },
    { code: "do", name: "Доминиканская Республика" },
    { code: "ec", name: "Эквадор" },
    { code: "eg", name: "Египет" },
    { code: "sv", name: "Сальвадор" },
    { code: "gq", name: "Экваториальная Гвинея" },
    { code: "er", name: "Эритрея" },
    { code: "ee", name: "Эстония" },
    { code: "sz", name: "Эсватини" },
    { code: "et", name: "Эфиопия" },
    { code: "fj", name: "Фиджи" },
    { code: "fi", name: "Финляндия" },
    { code: "fr", name: "Франция" },
    { code: "ga", name: "Габон" },
    { code: "gm", name: "Гамбия" },
    { code: "ge", name: "Грузия" },
    { code: "de", name: "Германия" },
    { code: "gh", name: "Гана" },
    { code: "gr", name: "Греция" },
    { code: "gd", name: "Гренада" },
    { code: "gt", name: "Гватемала" },
    { code: "gn", name: "Гвинея" },
    { code: "gw", name: "Гвинея-Бисау" },
    { code: "gy", name: "Гайана" },
    { code: "ht", name: "Гаити" },
    { code: "hn", name: "Гондурас" },
    { code: "hu", name: "Венгрия" },
    { code: "is", name: "Исландия" },
    { code: "in", name: "Индия" },
    { code: "id", name: "Индонезия" },
    { code: "ir", name: "Иран" },
    { code: "iq", name: "Ирак" },
    { code: "ie", name: "Ирландия" },
    { code: "il", name: "Израиль" },
    { code: "it", name: "Италия" },
    { code: "jm", name: "Ямайка" },
    { code: "jp", name: "Япония" },
    { code: "jo", name: "Иордания" },
    { code: "kz", name: "Казахстан" },
    { code: "ke", name: "Кения" },
    { code: "ki", name: "Кирибати" },
    { code: "kp", name: "Северная Корея" },
    { code: "kr", name: "Южная Корея" },
    { code: "kw", name: "Кувейт" },
    { code: "kg", name: "Киргизия" },
    { code: "la", name: "Лаос" },
    { code: "lv", name: "Латвия" },
    { code: "lb", name: "Ливан" },
    { code: "ls", name: "Лесото" },
    { code: "lr", name: "Либерия" },
    { code: "ly", name: "Ливия" },
    { code: "li", name: "Лихтенштейн" },
    { code: "lt", name: "Литва" },
    { code: "lu", name: "Люксембург" },
    { code: "mg", name: "Мадагаскар" },
    { code: "mw", name: "Малави" },
    { code: "my", name: "Малайзия" },
    { code: "mv", name: "Мальдивы" },
    { code: "ml", name: "Мали" },
    { code: "mt", name: "Мальта" },
    { code: "mh", name: "Маршалловы Острова" },
    { code: "mr", name: "Мавритания" },
    { code: "mu", name: "Маврикий" },
    { code: "mx", name: "Мексика" },
    { code: "fm", name: "Микронезия" },
    { code: "md", name: "Молдова" },
    { code: "mc", name: "Монако" },
    { code: "mn", name: "Монголия" },
    { code: "me", name: "Черногория" },
    { code: "ma", name: "Марокко" },
    { code: "mz", name: "Мозамбик" },
    { code: "mm", name: "Мьянма" },
    { code: "na", name: "Намибия" },
    { code: "nr", name: "Науру" },
    { code: "np", name: "Непал" },
    { code: "nl", name: "Нидерланды" },
    { code: "nz", name: "Новая Зеландия" },
    { code: "ni", name: "Никарагуа" },
    { code: "ne", name: "Нигер" },
    { code: "ng", name: "Нигерия" },
    { code: "mk", name: "Северная Македония" },
    { code: "no", name: "Норвегия" },
    { code: "om", name: "Оман" },
    { code: "pk", name: "Пакистан" },
    { code: "pw", name: "Палау" },
    { code: "ps", name: "Палестина" },
    { code: "pa", name: "Панама" },
    { code: "pg", name: "Папуа - Новая Гвинея" },
    { code: "py", name: "Парагвай" },
    { code: "pe", name: "Перу" },
    { code: "ph", name: "Филиппины" },
    { code: "pl", name: "Польша" },
    { code: "pt", name: "Португалия" },
    { code: "qa", name: "Катар" },
    { code: "ro", name: "Румыния" },
    { code: "ru", name: "Россия" },
    { code: "rw", name: "Руанда" },
    { code: "kn", name: "Сент-Китс и Невис" },
    { code: "lc", name: "Сент-Люсия" },
    { code: "vc", name: "Сент-Винсент и Гренадины" },
    { code: "ws", name: "Самоа" },
    { code: "sm", name: "Сан-Марино" },
    { code: "st", name: "Сан-Томе и Принсипи" },
    { code: "sa", name: "Саудовская Аравия" },
    { code: "sn", name: "Сенегал" },
    { code: "rs", name: "Сербия" },
    { code: "sc", name: "Сейшелы" },
    { code: "sl", name: "Сьерра-Леоне" },
    { code: "sg", name: "Сингапур" },
    { code: "sk", name: "Словакия" },
    { code: "si", name: "Словения" },
    { code: "sb", name: "Соломоновы Острова" },
    { code: "so", name: "Сомали" },
    { code: "za", name: "Южноафриканская Республика" },
    { code: "ss", name: "Южный Судан" },
    { code: "es", name: "Испания" },
    { code: "lk", name: "Шри-Ланка" },
    { code: "sd", name: "Судан" },
    { code: "sr", name: "Суринам" },
    { code: "se", name: "Швеция" },
    { code: "ch", name: "Швейцария" },
    { code: "sy", name: "Сирия" },
    { code: "tw", name: "Тайвань" },
    { code: "tj", name: "Таджикистан" },
    { code: "tz", name: "Танзания" },
    { code: "th", name: "Таиланд" },
    { code: "tl", name: "Восточный Тимор" },
    { code: "tg", name: "Того" },
    { code: "to", name: "Тонга" },
    { code: "tt", name: "Тринидад и Тобаго" },
    { code: "tn", name: "Тунис" },
    { code: "tr", name: "Турция" },
    { code: "tm", name: "Туркменистан" },
    { code: "tv", name: "Тувалу" },
    { code: "ug", name: "Уганда" },
    { code: "ua", name: "Украина" },
    { code: "ae", name: "Объединенные Арабские Эмираты" },
    { code: "gb", name: "Великобритания" },
    { code: "us", name: "Соединенные Штаты" },
    { code: "uy", name: "Уругвай" },
    { code: "uz", name: "Узбекистан" },
    { code: "vu", name: "Вануату" },
    { code: "va", name: "Ватикан" },
    { code: "ve", name: "Венесуэла" },
    { code: "vn", name: "Вьетнам" },
    { code: "ye", name: "Йемен" },
    { code: "zm", name: "Замбия" },
    { code: "zw", name: "Зимбабве" },
    { code: "xk", name: "Косово" }
]