export const allCountriesLT = [
    { code: "af", name: "Afganistanas" },
    { code: "al", name: "Albanija" },
    { code: "dz", name: "Alžyras" },
    { code: "ad", name: "Andora" },
    { code: "ao", name: "Angola" },
    { code: "ag", name: "Antigva ir Barbuda" },
    { code: "ar", name: "Argentina" },
    { code: "am", name: "Armėnija" },
    { code: "au", name: "Australija" },
    { code: "at", name: "Austrija" },
    { code: "az", name: "Azerbaidžanas" },
    { code: "bs", name: "Bahamos" },
    { code: "bh", name: "Bahreinas" },
    { code: "bd", name: "Bangladešas" },
    { code: "bb", name: "Barbadosas" },
    { code: "by", name: "Baltarusija" },
    { code: "be", name: "Belgija" },
    { code: "bz", name: "Belizas" },
    { code: "bj", name: "Beninas" },
    { code: "bt", name: "Butanas" },
    { code: "bo", name: "Bolivija" },
    { code: "ba", name: "Bosnija ir Hercegovina" },
    { code: "bw", name: "Botsvana" },
    { code: "br", name: "Brazilija" },
    { code: "bn", name: "Brunėjus" },
    { code: "bg", name: "Bulgarija" },
    { code: "bf", name: "Burkina Fasas" },
    { code: "bi", name: "Burundis" },
    { code: "cv", name: "Žaliasis Kyšulys" },
    { code: "kh", name: "Kambodža" },
    { code: "cm", name: "Kamerūnas" },
    { code: "ca", name: "Kanada" },
    { code: "cf", name: "Centrinės Afrikos Respublika" },
    { code: "td", name: "Čadas" },
    { code: "cl", name: "Čilė" },
    { code: "cn", name: "Kinija" },
    { code: "co", name: "Kolumbija" },
    { code: "km", name: "Komorai" },
    { code: "cg", name: "Kongo Respublika" },
    { code: "cd", name: "Kongo Demokratinė Respublika" },
    { code: "cr", name: "Kosta Rika" },
    { code: "hr", name: "Kroatija" },
    { code: "cu", name: "Kuba" },
    { code: "cy", name: "Kipras" },
    { code: "cz", name: "Čekija" },
    { code: "ci", name: "Dramblio Kaulo Krantas" },
    { code: "dk", name: "Danija" },
    { code: "dj", name: "Džibutis" },
    { code: "dm", name: "Dominika" },
    { code: "do", name: "Dominikos Respublika" },
    { code: "ec", name: "Ekvadoras" },
    { code: "eg", name: "Egiptas" },
    { code: "sv", name: "Salvadoras" },
    { code: "gq", name: "Pusiaujo Gvinėja" },
    { code: "er", name: "Eritrėja" },
    { code: "ee", name: "Estija" },
    { code: "sz", name: "Esvatinis" },
    { code: "et", name: "Etiopija" },
    { code: "fj", name: "Fidžis" },
    { code: "fi", name: "Suomija" },
    { code: "fr", name: "Prancūzija" },
    { code: "ga", name: "Gabonas" },
    { code: "gm", name: "Gambija" },
    { code: "ge", name: "Gruzija" },
    { code: "de", name: "Vokietija" },
    { code: "gh", name: "Gana" },
    { code: "gr", name: "Graikija" },
    { code: "gd", name: "Grenada" },
    { code: "gt", name: "Gvatemala" },
    { code: "gn", name: "Gvinėja" },
    { code: "gw", name: "Bisau Gvinėja" },
    { code: "gy", name: "Gajana" },
    { code: "ht", name: "Haitis" },
    { code: "hn", name: "Hondūras" },
    { code: "hu", name: "Vengrija" },
    { code: "is", name: "Islandija" },
    { code: "in", name: "Indija" },
    { code: "id", name: "Indonezija" },
    { code: "ir", name: "Iranas" },
    { code: "iq", name: "Irakas" },
    { code: "ie", name: "Airija" },
    { code: "il", name: "Izraelis" },
    { code: "it", name: "Italija" },
    { code: "jm", name: "Jamaika" },
    { code: "jp", name: "Japonija" },
    { code: "jo", name: "Jordanija" },
    { code: "kz", name: "Kazachstanas" },
    { code: "ke", name: "Kenija" },
    { code: "ki", name: "Kiribatis" },
    { code: "kp", name: "Šiaurės Korėja" },
    { code: "kr", name: "Pietų Korėja" },
    { code: "kw", name: "Kuveitas" },
    { code: "kg", name: "Kirgizija" },
    { code: "la", name: "Laosas" },
    { code: "lv", name: "Latvija" },
    { code: "lb", name: "Libanas" },
    { code: "ls", name: "Lesotas" },
    { code: "lr", name: "Liberija" },
    { code: "ly", name: "Libija" },
    { code: "li", name: "Lichtenšteinas" },
    { code: "lt", name: "Lietuva" },
    { code: "lu", name: "Liuksemburgas" },
    { code: "mg", name: "Madagaskaras" },
    { code: "mw", name: "Malavis" },
    { code: "my", name: "Malaizija" },
    { code: "mv", name: "Maldyvai" },
    { code: "ml", name: "Malis" },
    { code: "mt", name: "Malta" },
    { code: "mh", name: "Maršalo Salos" },
    { code: "mr", name: "Mauritanija" },
    { code: "mu", name: "Mauricijus" },
    { code: "mx", name: "Meksika" },
    { code: "fm", name: "Mikronezija" },
    { code: "md", name: "Moldova" },
    { code: "mc", name: "Monakas" },
    { code: "mn", name: "Mongolija" },
    { code: "me", name: "Juodkalnija" },
    { code: "ma", name: "Marokas" },
    { code: "mz", name: "Mozambikas" },
    { code: "mm", name: "Mianmaras" },
    { code: "na", name: "Namibija" },
    { code: "nr", name: "Nauru" },
    { code: "np", name: "Nepalas" },
    { code: "nl", name: "Nyderlandai" },
    { code: "nz", name: "Naujoji Zelandija" },
    { code: "ni", name: "Nikaragva" },
    { code: "ne", name: "Nigeris" },
    { code: "ng", name: "Nigerija" },
    { code: "mk", name: "Šiaurės Makedonija" },
    { code: "no", name: "Norvegija" },
    { code: "om", name: "Omanas" },
    { code: "pk", name: "Pakistanas" },
    { code: "pw", name: "Palau" },
    { code: "ps", name: "Palestina" },
    { code: "pa", name: "Panama" },
    { code: "pg", name: "Papua Naujoji Gvinėja" },
    { code: "py", name: "Paragvajus" },
    { code: "pe", name: "Peru" },
    { code: "ph", name: "Filipinai" },
    { code: "pl", name: "Lenkija" },
    { code: "pt", name: "Portugalija" },
    { code: "qa", name: "Kataras" },
    { code: "ro", name: "Rumunija" },
    { code: "ru", name: "Rusija" },
    { code: "rw", name: "Ruanda" },
    { code: "kn", name: "Sent Kitsas ir Nevis" },
    { code: "lc", name: "Sent Lusija" },
    { code: "vc", name: "Sent Vinsentas ir Grenadinai" },
    { code: "ws", name: "Samoa" },
    { code: "sm", name: "San Marinas" },
    { code: "st", name: "San Tomė ir Prinsipė" },
    { code: "sa", name: "Saudo Arabija" },
    { code: "sn", name: "Senegalas" },
    { code: "rs", name: "Serbija" },
    { code: "sc", name: "Seišeliai" },
    { code: "sl", name: "Siera Leonė" },
    { code: "sg", name: "Singapūras" },
    { code: "sk", name: "Slovakija" },
    { code: "si", name: "Slovėnija" },
    { code: "sb", name: "Saliamono Salos" },
    { code: "so", name: "Somalis" },
    { code: "za", name: "Pietų Afrika" },
    { code: "ss", name: "Pietų Sudanas" },
    { code: "es", name: "Ispanija" },
    { code: "lk", name: "Šri Lanka" },
    { code: "sd", name: "Sudanas" },
    { code: "sr", name: "Surinamas" },
    { code: "se", name: "Švedija" },
    { code: "ch", name: "Šveicarija" },
    { code: "sy", name: "Sirija" },
    { code: "tw", name: "Taivanas" },
    { code: "tj", name: "Tadžikistanas" },
    { code: "tz", name: "Tanzanija" },
    { code: "th", name: "Tailandas" },
    { code: "tl", name: "Rytų Timoras" },
    { code: "tg", name: "Togas" },
    { code: "to", name: "Tonga" },
    { code: "tt", name: "Trinidadas ir Tobagas" },
    { code: "tn", name: "Tunisas" },
    { code: "tr", name: "Turkija" },
    { code: "tm", name: "Turkmėnistanas" },
    { code: "tv", name: "Tuvalu" },
    { code: "ug", name: "Uganda" },
    { code: "ua", name: "Ukraina" },
    { code: "ae", name: "Jungtiniai Arabų Emyratai" },
    { code: "gb", name: "Jungtinė Karalystė" },
    { code: "us", name: "Jungtinės Valstijos" },
    { code: "uy", name: "Urugvajus" },
    { code: "uz", name: "Uzbekistanas" },
    { code: "vu", name: "Vanuatu" },
    { code: "va", name: "Vatikanas" },
    { code: "ve", name: "Venesuela" },
    { code: "vn", name: "Vietnamas" },
    { code: "ye", name: "Jemenas" },
    { code: "zm", name: "Zambija" },
    { code: "zw", name: "Zimbabvė" },
    { code: "xk", name: "Kosovas" }
]
